### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jun2mar** [TextRazor/textrazor-php#3]
Sir,
Got Error under.
testClassifier();
testEntityDictionary();

Also can you teach me how to return values on this following objects:

Word Object:
Lemma
PartofSpeech
stem

Relation:
Subject
Predicate
Object

Sorry having hard time reading Text Razor PHP Documentaion / Tutorial.
Kindly Help Please.

**Comment by crayston** [comment]
Hi Marjun, It looks like we're making progress on this through your email, I'll close this issue for now. Thanks.
