### ISSUE TITLE
Use Namespace to load textrazor instead of 'require'

### ISSUE THREAD

**Issue by juliquiron** [TextRazor/textrazor-php#6]
Hi all,
this is a feature request. Can you assign a Namespace to the PHP library in order to load it with 'use' statement.

thanks!

**Comment by crayston** [comment]
Hi! That's a good idea. 

Unfortunately I don't think there's any way we can add namespaces to the current TextRazor.php without breaking backwards compatibility with all of the existing callers of the library. We'll therefore need to wait until the next major iteration. In the mean time, the only file you need is TextRazor.php, so you could add the namespace wrapper around that file on your own fork.

Thanks for the feedback! I'll close this for now.

**Comment by sun** [comment]
If backwards-compatibility is the only concern, then we can easily solve that by supplying a legacy file loader.  Here's how:

1. Move each class into a separate, namespaced file (following PSR-1) and replace all `extends` statements accordingly.

    For instance:

        TextRazor.php                  =>    src/QueryBuilder.php


        class TextRazorQueryBuilder    =>    namespace TextRazor/Client;

                                             class QueryBuilder

1. Replace the current top-level API file `TextRazor.php` with a mere file loader for all apps that did not upgrade yet.

    For example:

  ```php
<?php

/** 
   * @file
   * Legacy file loading.
   *
   * This file exists for backwards-compatibility reasons only.
   * Please use the namespaced files instead.
   */

namespace TextRazor\Client {

    /**
     * Loads PSR-4-style classes of this package.
     *
     * @author Daniel Kudwien <daniel@netzstrategen.com>
     * @license MIT
     */
    function classloader($class) {
      static $ns_offset;

      if (strpos($class, __NAMESPACE__ . '\\') === 0) {
        if ($ns_offset === NULL) {
          $ns_offset = strlen(__NAMESPACE__) + 1;
        }
        include __DIR__ . '/src/' . strtr(substr($class, $ns_offset), '\\', '/') . '.php';
      }
    }

    spl_autoload_register(__NAMESPACE__ . '\classloader');
}

class TextRazorQueryBuilder extends \TextRazor\Client\QueryBuilder {}
class TextRazorSettings     extends \TextRazor\Client\Settings {}
class TextRazorConnection   extends \TextRazor\Client\Connection {}
class TextRazor             extends \TextRazor\Client\Client {}
class DictionaryManager     extends \TextRazor\Client\DictionaryManager {}
class ClassifierManager     extends \TextRazor\Client\ClassifierManager {}
class AccountManager        extends \TextRazor\Client\AccountManager {}

```

If you are going to accept this solution, I can happily create a PR that performs the full change.

**Comment by crayston** [comment]
Hey @sun, sorry I missed this last week. 

Thanks for the suggestion, that's a really good idea. We would certainly welcome your PR!
